name: Deploy EC2 and Manage S3

on:
  push:
    branches:
      - main

jobs:
  deploy-and-manage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Launch EC2 Instance
      run: |
        INSTANCE_ID=$(aws ec2 run-instances \
          --image-id ami-0e86e20dae9224db8 \
          --count 1 \
          --instance-type t2.micro \
          --key-name MyKeyPair \
          --security-group-ids sg-0383004c6de0a0ee7 \
          --query 'Instances[0].InstanceId' \
          --output text)
        echo "Instance ID: $INSTANCE_ID"

    - name: Create S3 Bucket
      run: |
        aws s3api create-bucket --bucket kn2122bucket --region ${{ secrets.AWS_REGION }}

    - name: Upload file to S3
      run: |
        echo "This is a test file" > testfile.txt
        aws s3 cp testfile.txt s3://kn2122bucket/testfile.txt
