name: S3 Upload Pipeline

on:
  push:
    branches:
      - main

jobs:
  upload_to_s3:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Create S3 Bucket (if it doesn't exist)
      run: |
        BUCKET_NAME="my-github-actions-bucket"
        aws s3api head-bucket --bucket $BUCKET_NAME 2>/dev/null || aws s3api create-bucket --bucket $BUCKET_NAME --region ${{ secrets.AWS_REGION }} --create-bucket-configuration LocationConstraint=${{ secrets.AWS_REGION }}
        echo "Bucket $BUCKET_NAME ensured."

    - name: Upload Object to S3
      run: |
        FILE_TO_UPLOAD="/home/ubuntu/newfolder/hello.txt"
        BUCKET_NAME="my-github-actions-bucket"
        aws s3 cp $FILE_TO_UPLOAD s3://$BUCKET_NAME/
        echo "File $FILE_TO_UPLOAD uploaded to s3://$BUCKET_NAME/"
